### ISSUE TITLE
Hey team! 我想试下这个项目 但是安装时候碰到问题 

### ISSUE THREAD

**Issue by 1984man** [Tencent/SessionAnalytics#1]
我对于前端部署不是太熟悉

我说下我的部署步骤：
1. cd /xxxx_path/SessionAnalytics/UserPathFront
2. nvm use 15
3. npm i -force
然后我得到了error
Not Found - GET https://registry.npmjs.org/@tencent%2feslint-config-tencent - Not found

**Comment by KANLON** [comment]
+1,我有同样的问题

**Comment by KANLON** [comment]
即使将镜像换成腾讯源的也不行，

当进入前端目录，我运行 ` npm i --force`   出现这个错误

```
npm WARN peer eslint-plugin-react@"7.x" from eslint-config-react-app@5.2.1
npm WARN node_modules/react-simple-verify/node_modules/eslint-config-react-app
npm WARN   eslint-config-react-app@"^5.1.0" from react-simple-verify@1.0.11
npm WARN   node_modules/react-simple-verify
npm WARN   1 more (react-scripts)
npm ERR! code E404
npm ERR! 404 Not Found - GET http://mirrors.cloud.tencent.com/npm/@tencent%2feslint-config-tencent - no such package available
npm ERR! 404
npm ERR! 404  '@tencent/eslint-config-tencent@^1.0.4' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```
这个源找不到 

http://mirrors.cloud.tencent.com/npm/@tencent%2feslint-config-tencent

**Comment by zcb1008** [comment]
上述问题可将.eslintrc.js文件中的@tencent/eslint-config-tencent注释掉或者删除，该包是eslint代码格式化，对项目无影响
![企业微信截图_16865370777765](https://github.com/Tencent/SessionAnalytics/assets/44228643/1a6a34d0-2b26-4caf-b8cc-da210dd4bc7a)

**Comment by zcb1008** [comment]
> 我对于前端部署不是太熟悉
> 
> 我说下我的部署步骤：
> 
> 1. cd /xxxx_path/SessionAnalytics/UserPathFront
> 2. NVM 使用 15
> 3. npm i -force 然后我得到了错误 未找到 - GET https://registry.npmjs.org/@tencent%2feslint-config-tencent - 未找到

上述问题可将.eslintrc.js文件中的@tencent/eslint-config-tencent注释掉或者删除，该包是eslint代码格式化，对项目无影响

**Comment by zcb1008** [comment]
> 即使将镜像换成腾讯源的也不行，
> 
> 当进入前端目录，我运行 ` npm i --force` 出现这个错误
> 
> ```
> npm WARN peer eslint-plugin-react@"7.x" from eslint-config-react-app@5.2.1
> npm WARN node_modules/react-simple-verify/node_modules/eslint-config-react-app
> npm WARN   eslint-config-react-app@"^5.1.0" from react-simple-verify@1.0.11
> npm WARN   node_modules/react-simple-verify
> npm WARN   1 more (react-scripts)
> npm ERR! code E404
> npm ERR! 404 Not Found - GET http://mirrors.cloud.tencent.com/npm/@tencent%2feslint-config-tencent - no such package available
> npm ERR! 404
> npm ERR! 404  '@tencent/eslint-config-tencent@^1.0.4' is not in this registry.
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> ```
> 
> 这个源找不到
> 
> http://mirrors.cloud.tencent.com/npm/@tencent%2feslint-config-tencent

问题可将.eslintrc.js文件中的@tencent/eslint-config-tencent注释掉或者删除，该包是eslint代码格式化，对项目无影响

**Comment by KANLON** [comment]
后端脚本少了一个用户表

```
CREATE TABLE `t_user` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `username` varchar(128) DEFAULT NULL COMMENT '用户',
  `password` varchar(190) DEFAULT null COMMENT '密码',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表' 
 ```

**Comment by zcb1008** [comment]
> 后端脚本少了一个用户表
> 
> ```
> CREATE TABLE `t_user` (
>   `id` int(10) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
>   `username` varchar(128) DEFAULT NULL COMMENT '用户',
>   `password` varchar(190) DEFAULT null COMMENT '密码',
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表' 
> ```
已提交对缺失用户表的更改
```
CREATE TABLE `t_user` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `username` varchar(128) DEFAULT NULL COMMENT '用户名',
  `password` varchar(128) DEFAULT NULL COMMENT '密码',
  `f_create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `f_update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 45 DEFAULT CHARSET = utf8 COMMENT = '用户名密码表'
```

**Comment by KANLON** [comment]
/excel /用户session分析日志上传模板.csv  这个文件不存在，麻烦可以上传一个吗？https://mdp-1251316161.cos.ap-guangzhou.myqcloud.com/excel%20%20%20%20%20%20/%E7%94%A8%E6%88%B7session%E5%88%86%E6%9E%90%E6%97%A5%E5%BF%97%E4%B8%8A%E4%BC%A0%E6%A8%A1%E6%9D%BF.csv  好像是这个链接，但是目前这个文件不存在了

**Comment by zcb1008** [comment]
> /excel /用户session分析日志上传模板.csv 这个文件不存在，麻烦可以上传一个吗？https://mdp-1251316161.cos.ap-guangzhou.myqcloud.com/excel%20%20%20%20%20%20/%E7%94%A8%E6%88%B7session%E5%88%86%E6%9E%90%E6%97%A5%E5%BF%97%E4%B8%8A%E4%BC%A0%E6%A8%A1%E6%9D%BF.csv 好像是这个链接，但是目前这个文件不存在了

模板已上传，包含中英文，存放于 /SessionAnalytics/UserPathFront/public 目录下

**Comment by nimuyuhan** [comment]
前端、后端都启动了，点注册报：
![image](https://github.com/Tencent/SessionAnalytics/assets/3031530/907f85a2-5118-48f3-aada-07052f2f5947)

**Comment by sessionpath** [comment]
> 前端、后端都启动了，点注册报： ![图像](https://user-images.githubusercontent.com/3031530/257690077-907f85a2-5118-48f3-aada-07052f2f5947.png)
需前后端联调一起，在axiso配置处添加后端地址
